export const char =[
    "./sw chars/darth sidious.jpeg",
    "./sw chars/bail organa.jpeg",
    "./sw chars/benni baro.jpeg",
    "./sw chars/cade.jpeg",
    "./sw chars/caleb dume.jpeg",
    "./sw chars/cid's parlor.jpeg",
    "./sw chars/clone-commander.jpeg",
    "./sw chars/crosshair.jpeg",
    "./sw chars/dr hemlock.jpeg",
    "./sw chars/dr-emerie-karr.jpeg",
    "./sw chars/gani riduli.jpeg",
    "./sw chars/gregor.jpeg",
    "./sw chars/grogu.jpeg",
    "./sw chars/gungi.jpeg",
    "./sw chars/halle burtoni.jpeg",
    "./sw chars/ipsium.jpeg",
    "./sw chars/Lt Nolan.jpeg",
    "./sw chars/lyana.jpeg",
    "./sw chars/mas amedda.jpeg",
    "./sw chars/mokko.jpeg",
    "./sw chars/nala se.jpeg",
    "./sw chars/omega.jpeg",
    "./sw chars/riyo chuchi.jpeg",
    "./sw chars/saw gerrera.jpeg",
    "./sw chars/shep-hazard.jpeg",

]